# numpy means numerical python
import numpy as np


In [2]:
import numpy as np

In [17]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr),arr.shape,arr.dtype)

a2=np.array([1,2,3,4,5,"aarti","ashwini","sakshi","kanchan"])
print(a2)
print(type(a2),a2.dtype,a2.shape)


[1 2 3 4 5 6 7]
<class 'numpy.ndarray'> (7,) int64
['1' '2' '3' '4' '5' 'aarti' 'ashwini' 'sakshi' 'kanchan']
<class 'numpy.ndarray'> <U21 (9,)


# 2d LIST

In [22]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[3,5,6]])
print(arr2D)
print(arr2D.shape)
print(arr2D.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 6]]
(4, 3)
int64


In [44]:
arr1=np.zeros((3,3),dtype="int64")
print(arr1,arr1.shape)

arr2=np.ones((3,3),dtype="int64")
print(arr2,arr2.shape)

arr3=np.full((3,3), 100)
print(arr3,arr3.shape)

arr4=np.eye((5))
print(arr4,arr4.shape)

arr5=np.arange(1,10)
print(arr5,arr5.shape)

arr6=np.linspace(1,100,3,dtype="int64")
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)
[1 2 3 4 5 6 7 8 9] (9,)
[  1  50 100] (3,)


# properties of NumPy arrays
## 1]shape=>printing dimensions of array
## 1]size=>prints size of array
## 1]dtype=>prints datatype of array
## 1]ndim=> gives total no of dimensions
## 1]astype=>use for typecasting


In [45]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(np.float64))


[1 2 3 4 5]
(5,)
5
int64
1
[1. 2. 3. 4. 5.]


# important operations of numpy arrays
## 1] reshaping
## 2] indexing 1D & 2D array
## 3] boolean & fancy indexing
## 4] slicing

In [63]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.reshape((3,2)))
print(arr.flatten())
print(arr[1][1])
print(arr[0][2])
arr=np.array([1,2,3,4,5])
print(arr)
print(arr[3])
idx=[0,3,4]
print(arr[idx])

# bollean indexing
arr=np.array([1,2,3,4,5,67])
print(arr[arr%2==0])

#slicing =>slicing is similar to python lists but internally different

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:6])
print(arr)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
5
3
[1 2 3 4 5]
4
[1 4 5]
[2 4]
[2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [69]:
#copy vs veiw of numpy arrays
py_list=[1,2,3,4,5,6]
sub_list=py_list[2:5]
3[2]=200
print(py_list,sub_list)

arr=np.array([1,2,3,4,5,6,7,8,9])
sub_arr=arr[1:6].copy()
sub_arr[2]=200
print(arr,sub_arr)


[1, 2, 3, 4, 5, 6] [3, 4, 200]
[1 2 3 4 5 6 7 8 9] [  2   3 200   5   6]


# common datatypes of numpy
## integer,float,bool,complex,string,object

In [80]:
arr=np.array([1,2,3,4,5,6,7],dtype="int32")
print(arr,arr.dtype)

arr=np.array([1,2,3.6,4,5,6,7])
print(arr,arr.dtype)

arr=np.array([1,2,3,4,5,6,7,"as"])
print(arr,arr.dtype)

arr=np.array([1,2,3,4,5,6,7],dtype="complex64")
print(arr,arr.dtype)

arr=np.array([3+2j])
print(arr,arr.dtype)

arr=np.array([{1,2,3},"prime",3.14])
print(arr,arr.dtype)

[1 2 3 4 5 6 7] int32
[1.  2.  3.6 4.  5.  6.  7. ] float64
['1' '2' '3' '4' '5' '6' '7' 'as'] <U21
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j] complex64
[3.+2.j] complex128
[{1, 2, 3} 'prime' 3.14] object


# multidimensional arrays

In [86]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_cols=np.sum(arr2D,axis=0)
print(sum_of_cols)
sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


# 3D Arrays

In [22]:
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,"\n",type(arr3D),"\n",arr3D.shape,"\n",arr3D.dtype,"\n",arr3D.ndim)

#indexing
print(arr3D[0,1,0])
print(arr3D[0,1,0:2])

#slicing
print(arr3D[0:2,0,0:2])# first rows 
print(arr3D[1:,2:,:])# first columns
print(arr3D[0:2,:,0])

# assigning values 
arr3D[0:2,0,0:2]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
 <class 'numpy.ndarray'> 
 (2, 3, 2) 
 int64 
 3
3
[3 4]
[[1 2]
 [7 8]]
[[[11 12]]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


# Vectorization
## vectorization performs operation on whole array

In [26]:
# square of an array
arr=np.array([1,2,3,4,5])
print(arr**2)

[ 1  4  9 16 25]


In [28]:
# addition of arrays
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)

[ 7  9 11 13 15]


# Broadcasting
## scalling arrays without using extra memory

In [32]:
arr=np.array([1,2,3,4,5])
print(arr+5)

arr1=np.array([1,2,3,4,5])
arr2=np.array([[6,7,8,9,10],[11,12,13,14,15]])
print(arr1.shape)
print(arr2.shape)
print(arr1+arr2)

[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 7  9 11 13 15]
 [12 14 16 18 20]]


# vector Normalization
## it uses broadcasting
## it basically means converting value to given range
## it incarease performance of ML algorithms
## standard  normalization (z-score) => formula(arr-mean)/SD

In [37]:
# normalize
arr=np.array([[1,2],[3,4]])
print(arr)
mean=np.mean(arr) # calculate mean
std=np.std(arr) # calculate Standard deviation

norm_arr=(arr-mean)/std
print(norm_arr)
print(mean)
print(std)

[[1 2]
 [3 4]]
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


# mathematical function
## aggreagation function

In [42]:
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))

15
120
1
5
3.0
1.4142135623730951
2.0
3.0
0
4


# power functions

In [43]:
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


# log & exponential

In [44]:
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# Round functions

In [49]:
print(np.round(3.15))
print(np.ceil(3.15))
print(np.floor(3.15))
print(np.trunc(3.15))

3.0
4.0
3.0
3.0


In [53]:
arr=np.array([1,2,3,34,5,6,4,5,4,5,4])
arr2=np.array([1,2,-3,34,5,-6,4,-5,4,5,4])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr2))

[ 1  2  3  4  5  6 34]
[ 1  2  3  4  4  4  5  5  5  6 34]
[ 1  2  3 34  5  6  4  5  4  5  4]
